does this maybe fix you
y u fail

```
 ---> 965ea09ff2eb
Step 2/6 : RUN true   && sed -i -e 's/v[[:digit:]]\.[[:digit:]]/edge/g' /etc/apk/repositories   && apk upgrade --update-cache --available   && apk add --no-cache font-noto   && apk add --no-cache firefox-esr   && adduser -s $(which firefox) -D firefox   && true
 ---> Running in 977b426796aa
fetch http://dl-cdn.alpinelinux.org/alpine/edge0/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge0/main: No such file or directory
WARNING: Ignoring APKINDEX.a488af6e.tar.gz: No such file or directory
fetch http://dl-cdn.alpinelinux.org/alpine/edge0/community/x86_64/APKINDEX.tar.gz
ERROR: http://dl-cdn.alpinelinux.org/alpine/edge0/community: No such file or directory
WARNING: Ignoring APKINDEX.1c19ffeb.tar.gz: No such file or directory
(1/3) Purging ssl_client (1.30.1-r2)
(2/3) Purging libtls-standalone (2.9.1-r0)
(3/3) Purging ca-certificates-cacert (20190108-r0)
Executing busybox-1.30.1-r2.trigger
OK: 5 MiB in 11 packages
fetch http://dl-cdn.alpinelinux.org/alpine/edge0/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge0/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge0/main/x86_64/APKINDEX.tar.gz: No such file or directory
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/edge0/community/x86_64/APKINDEX.tar.gz: No such file or directory
ERROR: unsatisfiable constraints:
  font-noto (missing):
    required by: world[font-noto]
The command '/bin/sh -c true   && sed -i -e 's/v[[:digit:]]\.[[:digit:]]/edge/g' /etc/apk/repositories   && apk upgrade --update-cache --available   && apk add --no-cache font-noto   && apk add --no-cache firefox-esr   && adduser -s $(which firefox) -D firefox   && true' returned a non-zero code: 1
##[error]Process completed with exit code 1.
```